# Generated by Django 4.2.5 on 2023-09-26 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='viewed_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lesson',
            name='viewed_time',
            field=models.DateTimeField(auto_now_add=True, default='2023-03-24'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='LessonView',
        ),
    ]
