# Generated by Django 4.2.5 on 2023-09-26 17:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0003_alter_lesson_duration_seconds'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='accesses',
            field=models.ManyToManyField(related_name='accessed_products', to=settings.AUTH_USER_MODEL),
        ),
    ]
